name: MCBotJS
version: 0.2.0
author: Uranium_Ape
main: uraniumape.mcbot.MCBot
api-version: 1.20
commands:
  mcbot:
    description: Admin commands for MCBot
    usage: /<command>
    permission: mcbot.admin